version: '3'
services:
  postgres:
    image: postgres
    restart: on-failure
    env_file:
      - .env
    ports:
      - 5400:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
