version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres
    restart: on-failure
    env_file:
      - ./server/.env
    ports:
      - 5400:5432
    networks:
      - taksanet
    volumes:
      - postgres-data:/var/lib/postgresql/data

  server:
    container_name: server
    build:
      dockerfile: ./Dockerfile
      context: ./server
    ports:
      - 3200:3200
    env_file:
      - ./server/.env
    networks:
      - taksanet
    depends_on:
      - postgres

networks:
  taksanet:
volumes:
  postgres-data:
