import cn from 'clsx'
import type { Metadata } from 'next'
import localFont from 'next/font/local'
import styles from './layout.module.css'

const euclidMedium = localFont({
	src: '../../fonts/EuclidCircularBMedium.ttf',
	display: 'swap'
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

const euclidRegular = localFont({
	src: [{
		path: '../../fonts/EuclidCircularBBold.ttf',
		weight: '600',
		style: 'normal',
	},
	{
		path: '../../fonts/EuclidCircularBLight.ttf',
		weight: '200',
		style: 'normal'
	},
	{
		path: '../../fonts/EuclidCircularBMedium.ttf',
		weight: '300',
		style: 'normal'
	},
	{
		path: '../../fonts/EuclidCircularBRegular.ttf',
		weight: '400',
		style: 'normal'
	}],
	display: 'swap',
	
	variable: '--font-euclidCircular'
})

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<main className={styles.main}>
			<div className={styles.taksa}>
				<img src='/taksa.svg' />
			</div>
			<div className={styles.curve}>
				<div className={styles.imgBefore} />
				<img src='/curve.svg' />
				<div className={styles.imgAfter} />
			</div>
			<div className={cn(styles.text, euclidMedium.className)}>
				<h1>Такса</h1>
				<h2>рада вам</h2>
			</div>
			<div className={styles.content}>{children}</div>
		</main>
	)
}
