'use client'
import cn from 'clsx'
import type { Metadata } from 'next'
import localFont from 'next/font/local'
import styles from './layout.module.css'
import { refreshJWT } from '@/functions/jwt'
import { useLayoutEffect } from 'react'
import { redirectToPage } from '@/functions/redirectToPage'
import { useRouter } from 'next/navigation'
import redirectByJWT from '@/functions/redirectByJWT'

const euclidMedium = localFont({
	src: '../../fonts/EuclidCircularBMedium.ttf',
	display: 'swap'
})

const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	redirectByJWT()
	return (
		<main className={styles.main}>
			<div className={styles.taksa}>
				<img src='/taksa.svg' />
			</div>
			<div className={styles.curve}>
				<div className={styles.imgBefore} />
				<img src='/curve.svg' />
				<div className={styles.imgAfter} />
			</div>
			<div className={cn(styles.text, euclidMedium.className)}>
				<h1>Такса</h1>
				<h2>рада вам</h2>
			</div>
			<div className={styles.content}>{children}</div>
		</main>
	)
}
